name: Node CI environment

on: [pull_request]

jobs:
  lint:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.19.0]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm login
        run:
          npm config set //registry.npmjs.org/:_authToken=$NPM_READONLY_AUTH_TOKEN
        env:
          NPM_READONLY_AUTH_TOKEN: ${{ secrets.NPM_READONLY_AUTH_TOKEN }}

      - name: npm install
        working-directory: ./
        run: npm i --ignore-scripts

      - name: Run ESLint
        run: npm run lint:eslint
